title: Link4Vets
baseURL: /
params:
  description: 'Link4Vets, een platform van dierenartsen voor dierenartsen.'
  layout_style: grid
  palette: green
  header:
    title: Link4Vets
    logo_img: images/l4vlogolong.jpg
    logo_img_alt: Link4Vets Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Over Link4vets
        url: /about
        style: link
      - label: Contact
        url: /contact
        style: link
  footer:
    content: '&copy; Link4Vets.'
    has_social: true
    social_links:
      - label: Instagram
        url: 'https://www.instagram.com/link4vets'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/link4vets'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - label: Facebook
        url: lorem-ipsum
        style: icon
        icon_class: fa-facebook
        new_window: true
        no_follow: false
        type: action
    has_subscribe: true
    subscribe_title: Schrijf je in voor Updates
    subscribe_content: >-
      Schrijf je in voor onze nieuwsbrief en ontvang maandelijks de
      belangrijkste updates over Link4Vets.
    subscribe_action: /subscribe-success
  favicon: images/clever-mango.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
